### ISSUE TITLE
Zend Framework trigger error

### ISSUE THREAD

**Issue by dlevel** [CodeaciousAU/zf2-oauth2-provider#1]
Hi, I found some issues when I made an upgrade of my version of Zend framework due to the way the service manager is used in the library.

I would like to make PR in order to remove this error by updating the way to use the service manager.

One of the case where the error can be found is when the ProviderFactory class is instanciated.

regards

**Comment by glennschmidt** [comment]
The zend framework deprecation errors have been resolved in release v1.0.3
